/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package audio_common_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message contains the audio meta data
<p>Source (audio_common_msgs/AudioInfo):
<pre>{@code
# This message contains the audio meta data

# Number of channels
uint8 channels
# Sampling rate [Hz]
uint32 sample_rate
# Audio format (e.g. S16LE)
string sample_format
# Amount of audio data per second [bits/s]
uint32 bitrate
# Audio coding format (e.g. WAVE, MP3)
string coding_format
}</pre>
*/
public class AudioInfo implements ROS2Message<AudioInfo>
{
   public static final java.lang.String name = "audio_common_msgs::msg::dds_::AudioInfo_";

   /**
      Number of channels
   */
   private byte channels_;
   /**
      Sampling rate [Hz]
   */
   private int sample_rate_;
   /**
      Audio format (e.g. S16LE)
   */
   private final StringBuilder sample_format_;
   /**
      Amount of audio data per second [bits/s]
   */
   private int bitrate_;
   /**
      Audio coding format (e.g. WAVE, MP3)
   */
   private final StringBuilder coding_format_;

   public AudioInfo()
   {
      sample_format_ = new StringBuilder();
      coding_format_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // channels_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // sample_rate_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * sample_format_.length()) + 1; // sample_format_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // bitrate_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * coding_format_.length()) + 1; // coding_format_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(channels_);
      buffer.writeInt(sample_rate_);
      buffer.writeString(sample_format_);
      buffer.writeInt(bitrate_);
      buffer.writeString(coding_format_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      channels_ = buffer.readByte();
      sample_rate_ = buffer.readInt();
      buffer.readString(sample_format_);
      bitrate_ = buffer.readInt();
      buffer.readString(coding_format_);

   }

   @Override
   public void set(AudioInfo from)
   {
      channels_ = from.channels_;
      sample_rate_ = from.sample_rate_;
      sample_format_.delete(0, sample_format_.length());
      sample_format_.insert(0, from.sample_format_);
      bitrate_ = from.bitrate_;
      coding_format_.delete(0, coding_format_.length());
      coding_format_.insert(0, from.coding_format_);

   }

   public byte getChannels()
   {
      return channels_;
   }

   public void setChannels(byte channels_)
   {
      this.channels_ = channels_;
   }

   public int getSampleRate()
   {
      return sample_rate_;
   }

   public void setSampleRate(int sample_rate_)
   {
      this.sample_rate_ = sample_rate_;
   }

   public StringBuilder getSampleFormat()
   {
      return sample_format_;
   }

   public java.lang.String getSampleFormatAsString()
   {
      return sample_format_.toString();
   }

   public void setSampleFormat(java.lang.String s)
   {
      this.sample_format_.delete(0, this.sample_format_.length());
      this.sample_format_.insert(0, s);
   }
   public int getBitrate()
   {
      return bitrate_;
   }

   public void setBitrate(int bitrate_)
   {
      this.bitrate_ = bitrate_;
   }

   public StringBuilder getCodingFormat()
   {
      return coding_format_;
   }

   public java.lang.String getCodingFormatAsString()
   {
      return coding_format_.toString();
   }

   public void setCodingFormat(java.lang.String s)
   {
      this.coding_format_.delete(0, this.coding_format_.length());
      this.coding_format_.insert(0, s);
   }

   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("AudioInfo {");
      builder.append("channels_=");
      builder.append(channels_);
      builder.append("sample_rate_=");
      builder.append(sample_rate_);
      builder.append("sample_format_=");
      builder.append(sample_format_.toString());
      builder.append("bitrate_=");
      builder.append(bitrate_);
      builder.append("coding_format_=");
      builder.append(coding_format_.toString());

      builder.append("}");
      return builder.toString();
   }
}