/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package audio_common_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (audio_common_msgs/AudioData):
<pre>{@code
uint8[] data
}</pre>
*/
public class AudioData implements ROS2Message<AudioData>
{
   public static final java.lang.String name = "audio_common_msgs::msg::dds_::AudioData_";

   private final IDLByteSequence data_;

   public AudioData()
   {
      data_ = new IDLByteSequence();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += data_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      data_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      data_.deserialize(buffer);

   }

   @Override
   public void set(AudioData from)
   {
      data_.set(from.data_);

   }

   public IDLByteSequence getData()
   {
      return data_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("AudioData {");
      builder.append("data_=");
      builder.append(data_);

      builder.append("}");
      return builder.toString();
   }
}