/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package audio_common_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (audio_common_msgs/AudioDataStamped):
<pre>{@code
std_msgs/Header header
audio_common_msgs/AudioData audio
}</pre>
*/
public class AudioDataStamped implements ROS2Message<AudioDataStamped>
{
   public static final java.lang.String name = "audio_common_msgs::msg::dds_::AudioDataStamped_";

   private final std_msgs.Header header_;
   private final audio_common_msgs.AudioData audio_;

   public AudioDataStamped()
   {
      header_ = new std_msgs.Header();
      audio_ = new audio_common_msgs.AudioData();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += audio_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      audio_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      audio_.deserialize(buffer);

   }

   @Override
   public void set(AudioDataStamped from)
   {
      header_.set(from.header_);
      audio_.set(from.audio_);

   }

   public std_msgs.Header getHeader()
   {
      return header_;
   }

   public audio_common_msgs.AudioData getAudio()
   {
      return audio_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("AudioDataStamped {");
      builder.append("header_=");
      builder.append(header_);
      builder.append("audio_=");
      builder.append(audio_);

      builder.append("}");
      return builder.toString();
   }
}