/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package example_interfaces.srv;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (example_interfaces/srv/AddTwoInts - Response):
<pre>{@code
int64 sum
}</pre>
*/
public class AddTwoInts_Response implements ROS2Message<AddTwoInts_Response>
{
   public static final String name = "example_interfaces::srv::dds_::AddTwoInts_Response_";

   private long sum_;

   public AddTwoInts_Response()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sum_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sum_);
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sum_ = buffer.readLong();
   }

   @Override
   public void set(AddTwoInts_Response from)
   {
      sum_ = from.sum_;
   }

   public long getSum()
   {
      return sum_;
   }

   public void setSum(long sum)
   {
      this.sum_ = sum;
   }

   @Override
   public String toString()
   {
      StringBuilder builder = new StringBuilder();
      builder.append("AddTwoInts_Response {");
      builder.append("sum_=");
      builder.append(sum_);
      builder.append("}");
      return builder.toString();
   }
}
