/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package example_interfaces.srv;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (example_interfaces/srv/SetBool - Response):
<pre>{@code
bool success
string message
}</pre>
*/
public class SetBool_Response implements ROS2Message<SetBool_Response>
{
   public static final String name = "example_interfaces::srv::dds_::SetBool_Response_";

   private boolean success_;
   private final StringBuilder message_ = new StringBuilder();

   public SetBool_Response()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // success_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // message_ length prefix
      currentAlignment += message_.length() + 1; // message_ data + null terminator

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(success_);
      buffer.writeString(message_);
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      success_ = buffer.readBoolean();
      buffer.readString(message_);
   }

   @Override
   public void set(SetBool_Response from)
   {
      success_ = from.success_;
      message_.setLength(0);
      message_.append(from.message_);
   }

   public boolean getSuccess()
   {
      return success_;
   }

   public void setSuccess(boolean success)
   {
      this.success_ = success;
   }

   public StringBuilder getMessage()
   {
      return message_;
   }

   @Override
   public String toString()
   {
      StringBuilder builder = new StringBuilder();
      builder.append("SetBool_Response {");
      builder.append("success_=");
      builder.append(success_);
      builder.append(", message_=");
      builder.append(message_);
      builder.append("}");
      return builder.toString();
   }
}
