/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package example_interfaces.srv;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (example_interfaces/srv/SetBool - Request):
<pre>{@code
bool data
}</pre>
*/
public class SetBool_Request implements ROS2Message<SetBool_Request>
{
   public static final String name = "example_interfaces::srv::dds_::SetBool_Request_";

   private boolean data_;

   public SetBool_Request()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // data_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(data_);
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      data_ = buffer.readBoolean();
   }

   @Override
   public void set(SetBool_Request from)
   {
      data_ = from.data_;
   }

   public boolean getData()
   {
      return data_;
   }

   public void setData(boolean data)
   {
      this.data_ = data;
   }

   @Override
   public String toString()
   {
      StringBuilder builder = new StringBuilder();
      builder.append("SetBool_Request {");
      builder.append("data_=");
      builder.append(data_);
      builder.append("}");
      return builder.toString();
   }
}
