/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package example_interfaces.srv;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (example_interfaces/srv/Trigger - Request):
<pre>{@code
# (empty request)
}</pre>
*/
public class Trigger_Request implements ROS2Message<Trigger_Request>
{
   public static final String name = "example_interfaces::srv::dds_::Trigger_Request_";

   public Trigger_Request()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      // Empty message still needs at least 1 byte for CDR padding
      return 0;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      // Empty request - nothing to serialize
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      // Empty request - nothing to deserialize
   }

   @Override
   public void set(Trigger_Request from)
   {
      // Empty request - nothing to copy
   }

   @Override
   public String toString()
   {
      return "Trigger_Request {}";
   }
}
