/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package sound_play_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
IMPORTANT: You should never have to generate this message yourself.
Use the sound_play::SoundClient C++ helper or the
sound_play.libsoundplay.SoundClient Python helper.
<p>Source (sound_play_msgs/SoundRequest):
<pre>{@code
# IMPORTANT: You should never have to generate this message yourself.
# Use the sound_play::SoundClient C++ helper or the
# sound_play.libsoundplay.SoundClient Python helper.

# Sounds
int8 BACKINGUP = 1
int8 NEEDS_UNPLUGGING = 2
int8 NEEDS_PLUGGING = 3
int8 NEEDS_UNPLUGGING_BADLY = 4
int8 NEEDS_PLUGGING_BADLY = 5

# Sound identifiers that have special meaning
int8 ALL = -1 # Only legal with PLAY_STOP
int8 PLAY_FILE = -2
int8 SAY = -3

int8 sound # Selects which sound to play (see above)

# Commands
int8 PLAY_STOP = 0 # Stop this sound from playing
int8 PLAY_ONCE = 1 # Play the sound once
int8 PLAY_START = 2 # Play the sound in a loop until a stop request occurs

int8 command # Indicates what to do with the sound

# Volume at which to play the sound, with 0 as mute and 1.0 as 100%.
float32 volume

string arg # file name or text to say
string arg2 # other arguments
}</pre>
*/
public class SoundRequest implements ROS2Message<SoundRequest>
{
   public static final java.lang.String name = "sound_play_msgs::msg::dds_::SoundRequest_";

   /**
      Sounds
   */
   public static final byte BACKINGUP = 1;
   public static final byte NEEDS_UNPLUGGING = 2;
   public static final byte NEEDS_PLUGGING = 3;
   public static final byte NEEDS_UNPLUGGING_BADLY = 4;
   public static final byte NEEDS_PLUGGING_BADLY = 5;
   /**
      Sound identifiers that have special meaning
   */
   public static final byte ALL = -1; // Only legal with PLAY_STOP
   public static final byte PLAY_FILE = -2;
   public static final byte SAY = -3;
   private byte sound_; // Selects which sound to play (see above)
   /**
      Commands
   */
   public static final byte PLAY_STOP = 0; // Stop this sound from playing
   public static final byte PLAY_ONCE = 1; // Play the sound once
   public static final byte PLAY_START = 2; // Play the sound in a loop until a stop request occurs
   private byte command_; // Indicates what to do with the sound
   /**
      Volume at which to play the sound, with 0 as mute and 1.0 as 100%.
   */
   private float volume_;
   private final StringBuilder arg_; // file name or text to say
   private final StringBuilder arg2_; // other arguments

   public SoundRequest()
   {
      arg_ = new StringBuilder();
      arg2_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // sound_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // command_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // volume_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * arg_.length()) + 1; // arg_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * arg2_.length()) + 1; // arg2_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(sound_);
      buffer.writeByte(command_);
      buffer.writeFloat(volume_);
      buffer.writeString(arg_);
      buffer.writeString(arg2_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sound_ = buffer.readByte();
      command_ = buffer.readByte();
      volume_ = buffer.readFloat();
      buffer.readString(arg_);
      buffer.readString(arg2_);

   }

   @Override
   public void set(SoundRequest from)
   {
      sound_ = from.sound_;
      command_ = from.command_;
      volume_ = from.volume_;
      arg_.delete(0, arg_.length());
      arg_.insert(0, from.arg_);
      arg2_.delete(0, arg2_.length());
      arg2_.insert(0, from.arg2_);

   }

   public byte getSound()
   {
      return sound_;
   }

   public void setSound(byte sound_)
   {
      this.sound_ = sound_;
   }

   public byte getCommand()
   {
      return command_;
   }

   public void setCommand(byte command_)
   {
      this.command_ = command_;
   }

   public float getVolume()
   {
      return volume_;
   }

   public void setVolume(float volume_)
   {
      this.volume_ = volume_;
   }

   public StringBuilder getArg()
   {
      return arg_;
   }

   public java.lang.String getArgAsString()
   {
      return arg_.toString();
   }

   public void setArg(java.lang.String s)
   {
      this.arg_.delete(0, this.arg_.length());
      this.arg_.insert(0, s);
   }
   public StringBuilder getArg2()
   {
      return arg2_;
   }

   public java.lang.String getArg2AsString()
   {
      return arg2_.toString();
   }

   public void setArg2(java.lang.String s)
   {
      this.arg2_.delete(0, this.arg2_.length());
      this.arg2_.insert(0, s);
   }

   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("SoundRequest {");
      builder.append("BACKINGUP=");
      builder.append(BACKINGUP);
      builder.append("NEEDS_UNPLUGGING=");
      builder.append(NEEDS_UNPLUGGING);
      builder.append("NEEDS_PLUGGING=");
      builder.append(NEEDS_PLUGGING);
      builder.append("NEEDS_UNPLUGGING_BADLY=");
      builder.append(NEEDS_UNPLUGGING_BADLY);
      builder.append("NEEDS_PLUGGING_BADLY=");
      builder.append(NEEDS_PLUGGING_BADLY);
      builder.append("ALL=");
      builder.append(ALL);
      builder.append("PLAY_FILE=");
      builder.append(PLAY_FILE);
      builder.append("SAY=");
      builder.append(SAY);
      builder.append("sound_=");
      builder.append(sound_);
      builder.append("PLAY_STOP=");
      builder.append(PLAY_STOP);
      builder.append("PLAY_ONCE=");
      builder.append(PLAY_ONCE);
      builder.append("PLAY_START=");
      builder.append(PLAY_START);
      builder.append("command_=");
      builder.append(command_);
      builder.append("volume_=");
      builder.append(volume_);
      builder.append("arg_=");
      builder.append(arg_.toString());
      builder.append("arg2_=");
      builder.append(arg2_.toString());

      builder.append("}");
      return builder.toString();
   }
}