/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package mobile_sensor_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (mobile_sensor_msgs/BiometricAuth):
<pre>{@code
std_msgs/Header header
bool success         # Did the fingerprint match?
uint8 user_id        # (Optional) Map fingerprints to specific users
}</pre>
*/
public class BiometricAuth implements ROS2Message<BiometricAuth>
{
   public static final java.lang.String name = "mobile_sensor_msgs::msg::dds_::BiometricAuth_";

   private final std_msgs.Header header_;
   private boolean success_; // Did the fingerprint match?
   private byte user_id_; // (Optional) Map fingerprints to specific users

   public BiometricAuth()
   {
      header_ = new std_msgs.Header();
      success_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // success_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // user_id_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      buffer.writeBoolean(success_);
      buffer.writeByte(user_id_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      success_ = buffer.readBoolean();
      user_id_ = buffer.readByte();

   }

   @Override
   public void set(BiometricAuth from)
   {
      header_.set(from.header_);
      success_ = from.success_;
      user_id_ = from.user_id_;

   }

   public std_msgs.Header getHeader()
   {
      return header_;
   }

   public boolean getSuccess()
   {
      return success_;
   }

   public void setSuccess(boolean success_)
   {
      this.success_ = success_;
   }

   public byte getUserId()
   {
      return user_id_;
   }

   public void setUserId(byte user_id_)
   {
      this.user_id_ = user_id_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("BiometricAuth {");
      builder.append("header_=");
      builder.append(header_);
      builder.append("success_=");
      builder.append(success_);
      builder.append("user_id_=");
      builder.append(user_id_);

      builder.append("}");
      return builder.toString();
   }
}