/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package mobile_sensor_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (mobile_sensor_msgs/NFCData):
<pre>{@code
std_msgs/Header header
string tag_id        # Unique Serial Number (UID)
string technology    # e.g., "NFC-A", "MifareClassic"
uint8[] ndef_payload # The raw data stored on the tag
}</pre>
*/
public class NFCData implements ROS2Message<NFCData>
{
   public static final java.lang.String name = "mobile_sensor_msgs::msg::dds_::NFCData_";

   private final std_msgs.Header header_;
   private final StringBuilder tag_id_; // Unique Serial Number (UID)
   private final StringBuilder technology_; // e.g., "NFC-A", "MifareClassic"
   private final IDLByteSequence ndef_payload_; // The raw data stored on the tag

   public NFCData()
   {
      header_ = new std_msgs.Header();
      tag_id_ = new StringBuilder();
      technology_ = new StringBuilder();
      ndef_payload_ = new IDLByteSequence();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * tag_id_.length()) + 1; // tag_id_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * technology_.length()) + 1; // technology_
      currentAlignment += ndef_payload_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      buffer.writeString(tag_id_);
      buffer.writeString(technology_);
      ndef_payload_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      buffer.readString(tag_id_);
      buffer.readString(technology_);
      ndef_payload_.deserialize(buffer);

   }

   @Override
   public void set(NFCData from)
   {
      header_.set(from.header_);
      tag_id_.delete(0, tag_id_.length());
      tag_id_.insert(0, from.tag_id_);
      technology_.delete(0, technology_.length());
      technology_.insert(0, from.technology_);
      ndef_payload_.set(from.ndef_payload_);

   }

   public std_msgs.Header getHeader()
   {
      return header_;
   }

   public StringBuilder getTagId()
   {
      return tag_id_;
   }

   public java.lang.String getTagIdAsString()
   {
      return tag_id_.toString();
   }

   public void setTagId(java.lang.String s)
   {
      this.tag_id_.delete(0, this.tag_id_.length());
      this.tag_id_.insert(0, s);
   }
   public StringBuilder getTechnology()
   {
      return technology_;
   }

   public java.lang.String getTechnologyAsString()
   {
      return technology_.toString();
   }

   public void setTechnology(java.lang.String s)
   {
      this.technology_.delete(0, this.technology_.length());
      this.technology_.insert(0, s);
   }
   public IDLByteSequence getNdefPayload()
   {
      return ndef_payload_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("NFCData {");
      builder.append("header_=");
      builder.append(header_);
      builder.append("tag_id_=");
      builder.append(tag_id_.toString());
      builder.append("technology_=");
      builder.append(technology_.toString());
      builder.append("ndef_payload_=");
      builder.append(ndef_payload_);

      builder.append("}");
      return builder.toString();
   }
}