/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package mobile_sensor_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (mobile_sensor_msgs/SamsungHealthHeartRate):
<pre>{@code
std_msgs/Header header
int32 status
int32 heart_rate
int32 ibi
int32 ibi_quality
}</pre>
*/
public class SamsungHealthHeartRate implements ROS2Message<SamsungHealthHeartRate>
{
   public static final java.lang.String name = "mobile_sensor_msgs::msg::dds_::SamsungHealthHeartRate_";

   private final std_msgs.Header header_;
   private int status_;
   private int heart_rate_;
   private int ibi_;
   private int ibi_quality_;

   public SamsungHealthHeartRate()
   {
      header_ = new std_msgs.Header();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // status_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // heart_rate_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // ibi_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // ibi_quality_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      buffer.writeInt(status_);
      buffer.writeInt(heart_rate_);
      buffer.writeInt(ibi_);
      buffer.writeInt(ibi_quality_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      status_ = buffer.readInt();
      heart_rate_ = buffer.readInt();
      ibi_ = buffer.readInt();
      ibi_quality_ = buffer.readInt();

   }

   @Override
   public void set(SamsungHealthHeartRate from)
   {
      header_.set(from.header_);
      status_ = from.status_;
      heart_rate_ = from.heart_rate_;
      ibi_ = from.ibi_;
      ibi_quality_ = from.ibi_quality_;

   }

   public std_msgs.Header getHeader()
   {
      return header_;
   }

   public int getStatus()
   {
      return status_;
   }

   public void setStatus(int status_)
   {
      this.status_ = status_;
   }

   public int getHeartRate()
   {
      return heart_rate_;
   }

   public void setHeartRate(int heart_rate_)
   {
      this.heart_rate_ = heart_rate_;
   }

   public int getIbi()
   {
      return ibi_;
   }

   public void setIbi(int ibi_)
   {
      this.ibi_ = ibi_;
   }

   public int getIbiQuality()
   {
      return ibi_quality_;
   }

   public void setIbiQuality(int ibi_quality_)
   {
      this.ibi_quality_ = ibi_quality_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("SamsungHealthHeartRate {");
      builder.append("header_=");
      builder.append(header_);
      builder.append("status_=");
      builder.append(status_);
      builder.append("heart_rate_=");
      builder.append(heart_rate_);
      builder.append("ibi_=");
      builder.append(ibi_);
      builder.append("ibi_quality_=");
      builder.append(ibi_quality_);

      builder.append("}");
      return builder.toString();
   }
}