/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package mobile_sensor_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (mobile_sensor_msgs/SamsungHealthSpO2):
<pre>{@code
std_msgs/Header header
int32 status
int32 spo2
}</pre>
*/
public class SamsungHealthSpO2 implements ROS2Message<SamsungHealthSpO2>
{
   public static final java.lang.String name = "mobile_sensor_msgs::msg::dds_::SamsungHealthSpO2_";

   private final std_msgs.Header header_;
   private int status_;
   private int spo2_;

   public SamsungHealthSpO2()
   {
      header_ = new std_msgs.Header();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // status_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // spo2_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      buffer.writeInt(status_);
      buffer.writeInt(spo2_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      status_ = buffer.readInt();
      spo2_ = buffer.readInt();

   }

   @Override
   public void set(SamsungHealthSpO2 from)
   {
      header_.set(from.header_);
      status_ = from.status_;
      spo2_ = from.spo2_;

   }

   public std_msgs.Header getHeader()
   {
      return header_;
   }

   public int getStatus()
   {
      return status_;
   }

   public void setStatus(int status_)
   {
      this.status_ = status_;
   }

   public int getSpo2()
   {
      return spo2_;
   }

   public void setSpo2(int spo2_)
   {
      this.spo2_ = spo2_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("SamsungHealthSpO2 {");
      builder.append("header_=");
      builder.append(header_);
      builder.append("status_=");
      builder.append(status_);
      builder.append("spo2_=");
      builder.append(spo2_);

      builder.append("}");
      return builder.toString();
   }
}