/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package mobile_sensor_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (mobile_sensor_msgs/TouchPoint):
<pre>{@code
uint32 id
float32 x
float32 y
float32 pressure
float32 major_axis
}</pre>
*/
public class TouchPoint implements ROS2Message<TouchPoint>
{
   public static final java.lang.String name = "mobile_sensor_msgs::msg::dds_::TouchPoint_";

   private int id_;
   private float x_;
   private float y_;
   private float pressure_;
   private float major_axis_;

   public TouchPoint()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // id_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // x_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // y_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // pressure_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // major_axis_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeInt(id_);
      buffer.writeFloat(x_);
      buffer.writeFloat(y_);
      buffer.writeFloat(pressure_);
      buffer.writeFloat(major_axis_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      id_ = buffer.readInt();
      x_ = buffer.readFloat();
      y_ = buffer.readFloat();
      pressure_ = buffer.readFloat();
      major_axis_ = buffer.readFloat();

   }

   @Override
   public void set(TouchPoint from)
   {
      id_ = from.id_;
      x_ = from.x_;
      y_ = from.y_;
      pressure_ = from.pressure_;
      major_axis_ = from.major_axis_;

   }

   public int getId()
   {
      return id_;
   }

   public void setId(int id_)
   {
      this.id_ = id_;
   }

   public float getX()
   {
      return x_;
   }

   public void setX(float x_)
   {
      this.x_ = x_;
   }

   public float getY()
   {
      return y_;
   }

   public void setY(float y_)
   {
      this.y_ = y_;
   }

   public float getPressure()
   {
      return pressure_;
   }

   public void setPressure(float pressure_)
   {
      this.pressure_ = pressure_;
   }

   public float getMajorAxis()
   {
      return major_axis_;
   }

   public void setMajorAxis(float major_axis_)
   {
      this.major_axis_ = major_axis_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("TouchPoint {");
      builder.append("id_=");
      builder.append(id_);
      builder.append("x_=");
      builder.append(x_);
      builder.append("y_=");
      builder.append(y_);
      builder.append("pressure_=");
      builder.append(pressure_);
      builder.append("major_axis_=");
      builder.append(major_axis_);

      builder.append("}");
      return builder.toString();
   }
}