/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package mobile_sensor_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (mobile_sensor_msgs/TouchArray):
<pre>{@code
std_msgs/Header header
TouchPoint[] touches
}</pre>
*/
public class TouchArray implements ROS2Message<TouchArray>
{
   public static final java.lang.String name = "mobile_sensor_msgs::msg::dds_::TouchArray_";

   private final std_msgs.Header header_;
   private final IDLObjectSequence<mobile_sensor_msgs.TouchPoint> touches_;

   public TouchArray()
   {
      header_ = new std_msgs.Header();
      touches_ = new IDLObjectSequence<mobile_sensor_msgs.TouchPoint>(mobile_sensor_msgs.TouchPoint.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += touches_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      touches_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      touches_.deserialize(buffer);

   }

   @Override
   public void set(TouchArray from)
   {
      header_.set(from.header_);
      touches_.set(from.touches_);

   }

   public std_msgs.Header getHeader()
   {
      return header_;
   }

   public IDLObjectSequence<mobile_sensor_msgs.TouchPoint> getTouches()
   {
      return touches_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("TouchArray {");
      builder.append("header_=");
      builder.append(header_);
      builder.append("touches_=");
      builder.append(touches_);

      builder.append("}");
      return builder.toString();
   }
}